### PR TITLE
Add 'push' flag in composer's image object

### PR DESCRIPTION
**Pull request by orviz**

### CODE REVIEW

**Comment by orviz** [comment]
@dianamariand92 rather than an array of services-to-push, I think it makes more sense to have the `push` as a flag inside the image's definition. Do you think this is ok from the web's perspective?

**Comment by orviz** [comment]
Addresses #47

**Comment by dianamariand92** [comment]
@orviz I think it is ok, I have already implemented it on the web. We must also define fields for the credential ID and the other variables in advanced mode.

**Review by dianamariand92 — APPROVED** [review]

**Comment by orviz** [comment]
@dianamariand92 you are totally right, I forgot to include here the credential part

I propose to have the following:
```yaml
    image:
      name: checkstyle/maven-builder-image
      registry:
        url: https://hub.docker.com/
        push: true
        credential_id: my-dockerhub-cred
```
having `credential_id` and registry's `url` per image, although the web will currently support one unique credential and registry

**Pull request merged**
